server:
  port: 8197
spring:
  data:
    mongodb:
      uri: mongodb://localhost/Nutritiondb
  application:
    name: SELFWELL-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost